language: node_js
node_js:
  - "8"
  - "9"
  - "10"

cache:
  directories:
  - "node_modules"

before_install:
  - travis_retry npm install
  - npm list --depth=0

script:
  - npm run lint
  - npm run test

after_success:
  - npm run coverage
